// Generated by CoffeeScript 1.4.0
(function() {
  var App, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  App = {};

  App.ListItem = (function(_super) {

    __extends(ListItem, _super);

    function ListItem() {
      return ListItem.__super__.constructor.apply(this, arguments);
    }

    ListItem.field('text', {
      "default": 'New Item'
    });

    ListItem.field('completed', {
      "default": false
    });

    ListItem.field('editing', {
      "default": false
    });

    return ListItem;

  })(Wraith.Model);

  App.List = (function(_super) {

    __extends(List, _super);

    function List() {
      this.removeCompleted = __bind(this.removeCompleted, this);

      this.setCompleted = __bind(this.setCompleted, this);

      this.remainingCount = __bind(this.remainingCount, this);

      this.completedCount = __bind(this.completedCount, this);
      return List.__super__.constructor.apply(this, arguments);
    }

    List.hasMany(App.ListItem, 'items');

    List.prototype.completedCount = function() {
      return this.get('items').all().reduce((function(prev, cur) {
        return prev + (cur.get('completed') ? 1 : 0);
      }), 0);
    };

    List.prototype.remainingCount = function() {
      return this.get('items').length() - this.completedCount();
    };

    List.prototype.setCompleted = function(completed) {
      var i, item, items, _i, _len;
      items = this.get('items').all();
      for (i = _i = 0, _len = items.length; _i < _len; i = ++_i) {
        item = items[i];
        item.set('completed', completed);
      }
      return this;
    };

    List.prototype.removeCompleted = function() {
      var i, id, ids, item, items, _i, _len;
      items = this.get('items').all();
      ids = (function() {
        var _i, _len, _results;
        _results = [];
        for (i = _i = 0, _len = items.length; _i < _len; i = ++_i) {
          item = items[i];
          if (item.get('completed')) {
            _results.push(item.get('_id'));
          }
        }
        return _results;
      })();
      for (_i = 0, _len = ids.length; _i < _len; _i++) {
        id = ids[_i];
        this.get('items').remove(id);
      }
      return this;
    };

    return List;

  })(Wraith.Model);

  App.TodoManager = (function(_super) {

    __extends(TodoManager, _super);

    function TodoManager() {
      this.inputKeypress = __bind(this.inputKeypress, this);

      this.clearCompleted = __bind(this.clearCompleted, this);

      this.toggleAll = __bind(this.toggleAll, this);

      this.itemKeypress = __bind(this.itemKeypress, this);

      this.itemEdit = __bind(this.itemEdit, this);

      this.itemDelete = __bind(this.itemDelete, this);

      this.updateToggleState = __bind(this.updateToggleState, this);

      this.itemToggle = __bind(this.itemToggle, this);
      return TodoManager.__super__.constructor.apply(this, arguments);
    }

    TodoManager.prototype.init = function() {
      TodoManager.__super__.init.call(this);
      this.list = this.registerModel(new App.List, 'list');
      this.items = this.list.get('items');
      this.items.create({
        text: 'Create a TodoMVC template',
        completed: true
      });
      this.items.create({
        text: 'Rule the web'
      });
      return this.items.create({
        text: 'Finish wraith'
      });
    };

    TodoManager.prototype.itemToggle = function(e) {
      e.model.set('completed', !e.model.get('completed'));
      return this.updateToggleState();
    };

    TodoManager.prototype.updateToggleState = function() {
      var $toggleAll;
      $toggleAll = this.$els['toggle-all'];
      if (this.items.length() === this.list.completedCount()) {
        return $toggleAll.checked = true;
      } else if (this.list.remainingCount() !== 0) {
        return $toggleAll.checked = false;
      }
    };

    TodoManager.prototype.itemDelete = function(e) {
      this.items.remove(e.model.get('_id'));
      return this.updateToggleState();
    };

    TodoManager.prototype.itemEdit = function(e) {
      return e.model.set('editing', !e.model.get('editing'));
    };

    TodoManager.prototype.itemKeypress = function(e) {
      var val;
      if (!(e.keyCode === 13 && (val = e.currentTarget.value) !== '')) {
        return;
      }
      e.model.set('text', val);
      return e.model.set('editing', false);
    };

    TodoManager.prototype.toggleAll = function(e) {
      return this.list.setCompleted(e.currentTarget.checked);
    };

    TodoManager.prototype.clearCompleted = function(e) {
      return this.list.removeCompleted();
    };

    TodoManager.prototype.inputKeypress = function(e) {
      var val;
      if (!(e.keyCode === 13 && (val = e.currentTarget.value) !== '')) {
        return;
      }
      this.items.create({
        text: val
      });
      e.currentTarget.value = '';
      return this.updateToggleState();
    };

    return TodoManager;

  })(Wraith.Controller);

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.App = App;

}).call(this);
