// Generated by CoffeeScript 1.4.0
(function() {
  var root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Wraith.Models.ListItem = (function(_super) {

    __extends(ListItem, _super);

    function ListItem() {
      return ListItem.__super__.constructor.apply(this, arguments);
    }

    ListItem.field('text', {
      "default": 'New Item'
    });

    ListItem.field('completed', {
      "default": false
    });

    ListItem.field('editing', {
      "default": false
    });

    return ListItem;

  })(Wraith.Model);

  Wraith.Models.List = (function(_super) {

    __extends(List, _super);

    function List() {
      this.removeCompleted = __bind(this.removeCompleted, this);

      this.setCompleted = __bind(this.setCompleted, this);

      this.remainingCount = __bind(this.remainingCount, this);

      this.completedCount = __bind(this.completedCount, this);
      return List.__super__.constructor.apply(this, arguments);
    }

    List.hasMany(Wraith.Models.ListItem, {
      as: 'items'
    });

    List.prototype.completedCount = function() {
      return this.get('items').all().reduce((function(prev, cur) {
        return prev + (cur.get('completed') ? 1 : 0);
      }), 0);
    };

    List.prototype.remainingCount = function() {
      return this.get('items').length() - this.completedCount();
    };

    List.prototype.setCompleted = function(completed) {
      var i, item, items, _i, _len;
      items = this.get('items').all();
      for (i = _i = 0, _len = items.length; _i < _len; i = ++_i) {
        item = items[i];
        item.set('completed', completed);
      }
      return this;
    };

    List.prototype.removeCompleted = function() {
      var i, item, items, _i, _len;
      items = this.get('items').all();
      for (i = _i = 0, _len = items.length; _i < _len; i = ++_i) {
        item = items[i];
        if (item.get('completed')) {
          this.get('items').remove(item.get('_id'));
        }
      }
      return this;
    };

    return List;

  })(Wraith.Model);

  Wraith.Views.TodoList = (function(_super) {

    __extends(TodoList, _super);

    function TodoList() {
      return TodoList.__super__.constructor.apply(this, arguments);
    }

    return TodoList;

  })(Wraith.View);

  Wraith.Controllers.TodoManager = (function(_super) {

    __extends(TodoManager, _super);

    function TodoManager() {
      this.inputKeypress = __bind(this.inputKeypress, this);

      this.toggleAll = __bind(this.toggleAll, this);

      this.itemKeypress = __bind(this.itemKeypress, this);

      this.itemEdit = __bind(this.itemEdit, this);

      this.itemDelete = __bind(this.itemDelete, this);

      this.updateToggleState = __bind(this.updateToggleState, this);

      this.itemToggle = __bind(this.itemToggle, this);

      this.getModelIdFromEl = __bind(this.getModelIdFromEl, this);
      return TodoManager.__super__.constructor.apply(this, arguments);
    }

    TodoManager.prototype.view_events = [
      {
        type: 'click',
        selector: 'button.destroy',
        cb: 'itemDelete'
      }, {
        type: 'click',
        selector: '#todo-list input[type=checkbox]',
        cb: 'itemToggle'
      }, {
        type: 'dblclick',
        selector: 'label',
        cb: 'itemEdit'
      }, {
        type: 'keypress',
        selector: 'input.edit',
        cb: 'itemKeypress'
      }, {
        type: 'change',
        selector: '#toggle-all',
        cb: 'toggleAll'
      }, {
        type: 'keypress',
        selector: 'input#new-todo',
        cb: 'inputKeypress'
      }
    ];

    TodoManager.prototype.init = function() {
      TodoManager.__super__.init.call(this);
      this.registerModel('list', new Wraith.Models.List);
      this.list = this.models['list'];
      this.items = this.list.get('items');
      this.items.create({
        text: 'Create a TodoMVC template',
        completed: true
      });
      this.items.create({
        text: 'Rule the web'
      });
      return this.items.create({
        text: 'Finish wraith'
      });
    };

    TodoManager.prototype.getModelIdFromEl = function(el) {
      var $view;
      $view = this.findViewByElement(el);
      return this.findIdByView($view);
    };

    TodoManager.prototype.itemToggle = function(e) {
      var id, item;
      id = this.getModelIdFromEl(e.currentTarget);
      item = this.items.findById(id);
      item.set('completed', !item.get('completed'));
      return this.updateToggleState();
    };

    TodoManager.prototype.updateToggleState = function() {
      if (this.items.length() === this.list.completedCount()) {
        this.$els['toggle-all'].attr('checked', true);
      } else if (this.list.remainingCount() !== 0) {
        this.$els['toggle-all'].removeAttr('checked');
      }
      return this;
    };

    TodoManager.prototype.itemDelete = function(e) {
      return items.remove(this.getModelIdFromEl(e.currentTarget));
    };

    TodoManager.prototype.itemEdit = function(e) {
      var id, item;
      id = this.getModelIdFromEl(e.currentTarget);
      item = this.items.findById(id);
      item.set('completed', false);
      return item.set('editing', !item.get('editing'));
    };

    TodoManager.prototype.itemKeypress = function(e) {
      var id, item, val;
      if (!(e.keyCode === 13 && (val = e.currentTarget.value) !== '')) {
        return;
      }
      id = this.getModelIdFromEl(e.currentTarget);
      item = this.items.findById(id);
      item.set('text', val);
      return item.set('editing', false);
    };

    TodoManager.prototype.toggleAll = function(e) {
      var checked;
      checked = e.currentTarget.checked;
      this.list.setCompleted(checked);
      if (checked) {
        return this.$els['toggle-all'].attr('checked', true);
      } else {
        return this.$els['toggle-all'].removeAttr('checked');
      }
    };

    TodoManager.prototype.inputKeypress = function(e) {
      var val;
      if (!(e.keyCode === 13 && (val = e.currentTarget.value) !== '')) {
        return;
      }
      this.items.create({
        text: val
      });
      return e.currentTarget.value = '';
    };

    return TodoManager;

  })(Wraith.Controller);

}).call(this);
